spring:
  datasource:
    url: jdbc:mysql://localhost:3307/store_info??createDatabaseIfNotExist=true
    username: root
    password: Steffina1!

    #JPA sETTINGS
    jpa:
      hibernate.ddl-auto: create